name: lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pre-commit
        python -m pip install --editable .
        python -m pip install --upgrade pytest
        python -m pip install --upgrade pylint
    - name: Lint with black and flake8
      run: pre-commit run --all-files
    - name: Lint with pylint
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        pylint --errors-only src/rate_my_project
        # Exit-zero treats all errors as warnings.
        pylint --exit-zero src/rate_my_project > pylint_results.txt
    - name: Upload pylint results
      uses: actions/upload-artifact@v2
      with:
        name: pylint_results
        path: pylint_results.txt
